version: "2"
services:
  geth-bootnode:
    hostname: geth-bootnode
    environment: 
      - nodekeyhex=08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b #Needs to be fix, so that the miners know the resulting enode id
    build:
      context: ./bootnode
    ports: 
      - 30303:30303
      - 8545:8545
      - 5545:5545
      - 6545:6545
volumes:
  eth-data-1:
